services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=${SERVER_URL}
      - PYWORKER_URL=${PYWORKER_URL}

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT:-5000}:5000"
    depends_on:
      - pyworker
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - HOST=${HOST}
      - SERVER_URL=${SERVER_URL}
      - PYWORKER_URL=${PYWORKER_URL}
    volumes:
      - uploads-folder:/app/uploads-folder
      - saved_data:/app/saved_data

  pyworker:
    build:
      context: ./pyworker
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - uploads-folder:/app/uploads-folder
      - saved_data:/app/saved_data
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}

volumes:
  pgdata:
  uploads-folder:
  saved_data:
